services:
  web:
    container_name: ${COMPOSE_PROJECT_NAME}
    build:
      context: ..
      dockerfile: docker/Dockerfile
    working_dir: /usr/src/app
    stdin_open: true
    user: node
    volumes:
      - ../:/usr/src/app
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:${VIRTUAL_HOST}'
      - 'traefik.docker.network=${PROXY_NETWORK}'
      - 'traefik.port=${VIRTUAL_PORT}'
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: postgres:16
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  redis:
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    image: redis:7
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
networks:
  default:
    external: true
    name: ${PROXY_NETWORK}

volumes:
  db:
