services:
  web:
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: always
    build:
      context: ..
      dockerfile: docker/prod.Dockerfile
    user: node
    ports:
      - "${VIRTUAL_PORT}:${VIRTUAL_PORT}"
  redis:
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    image: redis:7
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
